# 書本編輯 

跑出單一章節的方法:可以透過上方的Knit按鍵，或是用以下方法生成電子書(gitbook)
```{r 簡介1,eval=FALSE, include=TRUE}
bookdown::preview_chapter("01-intro.rmd", output_format="bookdown::gitbook")
```
## Markdown 語法(syntax)
詳見[林茂廷老師上課講義](https://bookdown.org/tpemartin/rmarkdown_intro/markdown-syntax.html#e59fbae69cace8aa9ee6b395)、
[markdown_cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)、或是[bookdown電子書範例](https://bookdown.org/yihui/bookdown/markdown-syntax.html#inline-formatting)。  

注意換行要在結束句輸入「兩」個空格，才換行。不然就要按兩次enter鍵。  
一個空格只是單純的空格，「兩」個空格才會有新的意義，如換行或內縮（在列點時用）。  
## 參考文獻引注
建立.bib檔，範例程式中已有`book.bib`(圖書),`packages.bib`(R套件)，可以自行做增刪。  
在index.Rmd
```{r eval=FALSE}
--- 
title: "A Minimal Book Example"
author: "Yihui Xie"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
# 設定參考文獻!
## 要讀取的檔案
bibliography: [book.bib, packages.bib]
biblio-style: apalike
#設定為 yes，才有超連結功能
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---
```
.bib內的格式
```{r eval=FALSE}
@Manual{R-base, #名稱(key) 
  title = {R: A Language and Environment for Statistical
    Computing}, # 文獻類別 : article, book, manual
  author = {{R Core Team}}, #作者
  organization = {R Foundation for Statistical Computing}, #機構
  address = {Vienna, Austria},
  year = {2016}, #年分
  url = {https://www.R-project.org/}, #網址
}
```
這裡引用[@R-base](`[@R-base]`)`[@名稱(key)]`  
最後一個檔案(範例中為`06-references.Rmd`)，可僅用一行程式表達，
```{r eval=FALSE}
`r if (knitr::is_html_output()) '# References {-}'`
```



### 有趣的互動應用{-}
Shiny app example:
```{r include=TRUE}
knitr::include_app("https://yihui.shinyapps.io/miniUI/", 
  height = "600px")
```
口罩地圖
```{r include=TRUE}
knitr::include_app("https://mask.goodideas-studio.com/", 
  height = "600px")
```

